  - name: install mariadb and mysql
    apt:
      name:
        - mariadb-server
        - python3-pymysql
      state: present

  - name: create and config 99-openstock.cnf
    template:
      src: 99-openstack.cnf.j2
      dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf

  - name: restart mysql service
    service:
      name: mysql
      state: restarted
